### ISSUE TITLE
Need a way to disable

### ISSUE THREAD

**Issue by mwoods79** [rondale-sc/vim-spacejam#4]
I am working in a codebase where every file has whitespace at the end of the file.  It would be nice to disable this plugin.  Both as a global toggle, and as a way to set the .vimrc.local in dot-matrix to disable.

**Comment by jonafato** [comment]
You can disable the plugin by putting `let g:loaded_spacejam = 1` in your `.vimrc` (or `.vimrc.local`).

**Comment by rondale-sc** [comment]
Thanks @jonafato
